[project]
name = "minecraft-launcher"
version = "0.1.0"
description = "A Minecraft Launcher Written in Python"
requires-python = ">=3.14"
dependencies = [
    "athreading>=0.3.0",
    "docutils>=0.23",
    "json5>=0.15.0",
    "loguru>=0.7.3",
    "msgspec>=0.20.0",
    "niquests~=3.20",
    "platformdirs>=4.10",
    "prompt-toolkit>=3.0.52",
    "psutil>=7.2.2",
    "pyyaml>=6.0.3",
    #    "rapidnbt>=1.3.5",
    "readchar>=4.2.2",
    "rich~=15.0",
    "textual>=8.2.8",
    "tqdm>=4.70.0",
    "typeguard>=4.5.1",
    "typer~=0.27",
    "winloop>=0.5.0; sys_platform == 'win32'",
    "uvloop>=0.5.0; sys_platform != 'win32'",
    "xxhash>=3.7.0",
    "yarl>=1.24.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "aiomonitor>=0.7.1",
    "memory-profiler>=0.61.0",
    "puremagic>=2.2.0",
    "py-spy>=0.4.2",
    "setuptools<75.0",
]
