[project]
name = "minecraft-launcher"
version = "0.1.0"
description = "A Minecraft Launcher Written in Python"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "click>=8.4.2",
    "furl>=2.1.4",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "msgspec>=0.20.0",
    "niquests>=3.20.0",
    "platformdirs>=4.10",
    "psutil>=7.2.2",
    "pyyaml>=6.0.3",
    "rich~=15.0",
    "threadedprocess>=0.0.5",
    "tqdm>=4.68.3",
    "trogon[typer]>=0.6.0",
    "typeguard>=4.5.1",
    "typer~=0.26",
    "winloop>=0.5.0",
    "xxhash>=3.7.0",
    "yarl>=1.24.0",
    "zstandard>=0.25.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "aiomonitor>=0.7.1",
    "memory-profiler>=0.61.0",
    "py-spy>=0.4.2",
]
